"""Supplementary tables: compact LaTeX (results/figures/supp_tables.tex) and the full Supplementary Data 1 workbook
(results/figures/Supplementary_Data_1.xlsx). usage: python F_supp_tables.py"""
import numpy as np
import pandas as pd

R, OUT = "results", "results/figures"


def tex_table(df, label, caption, colfmt=None, fontsize="\\footnotesize"):
    colfmt = colfmt or ("l" * df.shape[1])
    lines = [r"\begin{table}[htbp]", r"\centering" + fontsize, rf"\caption{{{caption}}}\label{{{label}}}",
             rf"\begin{{tabular}}{{@{{}}{colfmt}@{{}}}}", r"\toprule", " & ".join(df.columns) + r"\\", r"\midrule"]
    for _, r in df.iterrows():
        cells = [str(v) for v in r.values]
        cells = ["$-$" + c[1:] if c.startswith("-") and c[1:2].isdigit() else c for c in cells]
        lines.append(" & ".join(cells) + r"\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


tex = ["% generated by analysis/F_supp_tables.py"]
sheets = {}

# S2: exact WF bias (single-genome counts), max |bias| by B, kind, Ts
a = pd.concat([pd.read_csv(f"{R}/A10/{f}", sep="\t") for f in
               ("A10a_bias_N200_Ts8.tsv", "A10a_bias_N200_Ts16.tsv", "A10a_bias_N400_Ts8.tsv")])
sheets["S2_exact_WF_bias"] = a
s2 = (a[a.N.isin([400]) | (a.Ts_in_N == 16)].groupby(["counts", "Ts_in_N", "kind", "B"]).bias_in_N
      .agg(lambda x: x.iloc[np.argmax(np.abs(x.values))]).unstack("B").reset_index())
s2.columns = ["counts", "$T_s/N$", "switch-off"] + [f"$B$={b:g}" for b in s2.columns[3:]]
s2["counts"] = s2["counts"].map({"all": "single genome", "fixed_only": "fixed only"})
for c in s2.columns[3:]:
    s2[c] = s2[c].map(lambda v: f"{v:+.2f}")
s2["$T_s/N$"] = s2["$T_s/N$"].map(lambda v: f"{v:g}")
tex.append(tex_table(s2, "tab:wf", "Exact Wright--Fisher bias of $\\hat T = T_s(1-\\hat\\rho)$, in units of $N$ generations: the "
                     "largest bias over four switch-off times, by conversion strength $B$. $N = 400$ ($T_s = 8N$) and $N = 200$ "
                     "($T_s = 16N$). For $N_e = 10^4$ and $g = 25$~y, $1N$ = 0.25~Myr.", "lllrrrrr"))

# S3: bottleneck
b = pd.read_csv(f"{R}/A10/A10d_bottleneck_N300.tsv", sep="\t")
sheets["S3_bottleneck"] = b
s3 = b[b.B0 == 1.0].copy()
s3["bottleneck"] = s3.bottleneck_at_N0.map({"none": "none", "1.8": "after ($\\sim$0.9 Mya)", "5.6": "during switch-off",
                                             "8.0": "before ($\\sim$4 Mya)"}).fillna(s3.bottleneck_at_N0.astype(str))
s3 = s3.pivot_table(index=["bottleneck", "size_frac"], columns="kind", values="bias_N0").reset_index()
s3["step (Myr)"] = (s3["step"] * 0.5).map(lambda v: f"{v:+.2f}")
s3["gradual (Myr)"] = (s3["ramp"] * 0.5).map(lambda v: f"{v:+.2f}")
s3 = s3[["bottleneck", "size_frac", "step (Myr)", "gradual (Myr)"]].rename(columns={"size_frac": "size (fraction of $N_0$)"})
tex.append(tex_table(s3, "tab:bottleneck", "Bias of the switch-off estimate under a bottleneck (exact Wright--Fisher; 0.1-Myr "
                     "bottleneck; $B_0 = 1$; converted with $N_0 = 2\\times10^4$, $g = 25$~y; true $T_{\\mathrm{off}}$ = 2.8~Mya). "
                     "Negative: the estimate is too young.", "lrrr"))

# S4: SLiM
sl = pd.read_csv(f"{R}/A10b/A10b_estimates.tsv", sep="\t")
sheets["S4_SLiM"] = sl
s4 = sl.assign(**{"true $T_{off}/T_s$": sl.T_true / 4000, "estimate": (sl.T_hat / 4000).map(lambda v: f"{v:.2f}"),
                  "95\\% interval": [f"{a / 4000:.2f}--{b / 4000:.2f}" for a, b in zip(sl.T_lo, sl.T_hi)],
                  "end excess": sl.end_excess.map(lambda v: f"{v:.2f}")})
s4 = s4[["bias", "end excess", "true $T_{off}/T_s$", "estimate", "95\\% interval"]].rename(columns={"bias": "conversion bias"})
s4["true $T_{off}/T_s$"] = s4["true $T_{off}/T_s$"].map(lambda v: f"{v:.2f}")
tex.append(tex_table(s4, "tab:slim", "Forward simulations (SLiM): switch-off estimates from 40 pooled replicates per scenario, "
                     "with bootstrap intervals. End excess: W$\\to$S log-odds excess of the permanent end segment over the interior.",
                     "lrrrr"))

# S5: assemblies and haplotypes (simple statistic)
c = pd.read_csv(f"{R}/A14/A14_logodds_cells.tsv", sep="\t")
sheets["S5_assembly_haplotype"] = c
s5 = c[c.side == "both"].pivot_table(index="first_Mb", columns="cell", values="T").reset_index()
s5 = s5.rename(columns={"first_Mb": "first Mb", "chm13_8way": "CHM13 (8-way)", "h16a": "h16a", "h16b": "h16b"})
for col in s5.columns[1:]:
    s5[col] = s5[col].map(lambda v: f"{v:.2f}")
tex.append(tex_table(s5, "tab:cells", "Switch-off estimates (Mya) from the simple within-human statistic (both flanks) for the "
                     "reference assembly and two haplotype sets.", "lrrr"))

# S6: lineage-sorting simulations
hp = pd.read_csv(f"{R}/A10/A10c_Hpoly.tsv", sep="\t")
hs = pd.read_csv(f"{R}/A10/A10c_Hsub.tsv", sep="\t")
sheets["S6_ILS_Hpoly"] = hp
sheets["S6_ILS_Hsub"] = hs
s6 = hp[hp.y_cM.isin([0.001, 0.1, 1.0, 10.0])].pivot_table(index=["Delta_Myr", "c"], columns="y_cM", values="fold").reset_index()
s6.columns = ["$\\Delta$ (Myr)", "$c$"] + [f"{y:g} cM" for y in s6.columns[2:]]
for col in s6.columns[2:]:
    s6[col] = s6[col].map(lambda v: f"{v:.2f}")
tex.append(tex_table(s6, "tab:ils", "Predicted ILS fold (over genome) under an ancestral fused/unfused polymorphism of duration "
                     "$\\Delta$ spanning the split, with recombination between arrangements at a fraction $c$ of normal, by genetic "
                     "distance from the junction (msprime, 50{,}000 replicates). Substrate model, fold for $k$ = 1.2, 1.5, 2, 3: "
                     + ", ".join(f"{v:.2f}" for v in hs.set_index("k").fold.reindex([1.2, 1.5, 2.0, 3.0])) + ".", "llrrrr"))

# data-only sheets
for nm, path in (("S7_pseudo_fusions_pooled", f"{R}/A4/A4_pseudo_chimp_human+pan+gorilla.tsv"),
                 ("S8_two_sides_LR", f"{R}/A4/A4b_sides_chimp.tsv"),
                 ("S9_single_reference", f"{R}/A15/A15_flank_calibrated.tsv"),
                 ("S10_recomb_calibration", f"{R}/A12/A12b_models.tsv"),
                 ("S11_orthologue_strength", f"{R}/A16/A16c_orthologue_strength.tsv"),
                 ("S12_present_day_B", f"{R}/A6/B_by_region_afr.tsv"),
                 ("S13_B_by_DSB", f"{R}/A12c/B_by_dsbbin_afr.tsv"),
                 ("S14_time_strata", f"{R}/A7/A7c_corrected.tsv"),
                 ("S15_ILS_junction", f"{R}/A16/A16d_ils_junction.tsv")):
    sheets[nm] = pd.read_csv(path, sep="\t")
with pd.ExcelWriter(f"{OUT}/Supplementary_Data_1.xlsx") as xw:
    readme = pd.DataFrame({"sheet": list(sheets), "rows": [len(v) for v in sheets.values()]})
    readme.to_excel(xw, sheet_name="README", index=False)
    for k, v in sheets.items():
        v.to_excel(xw, sheet_name=k[:31], index=False)
open(f"{OUT}/supp_tables.tex", "w").write("\n".join(tex))
print("ok", list(sheets))
