"""Generate manuscript/numbers.tex from results/figures/stats.json (run after F_make_figures.py --only 4)."""
import json
import sys

s = json.load(open(sys.argv[1]))
out = sys.argv[2]
b, c = s.get("fig4b"), s.get("fig4c")
L = ["% generated by analysis/gen_numbers.py from results/figures/stats.json"]
if b:
    L += [rf"\newcommand{{\slimCov}}{{{b['n_cov']}}}", rf"\newcommand{{\slimN}}{{{b['n']}}}",
          rf"\newcommand{{\slimBias}}{{{b['mean_abs_bias_Ts']:.3f}}}"]
if c:
    fmt = lambda p: f"{p:.2g}" if p >= 0.001 else f"{p:.1e}"
    verdict = "consistent with the data" if c["p_emp"] >= 0.05 else "rejected"
    L += [rf"\newcommand{{\LRflank}}{{{c['LR']:.1f}}}", rf"\newcommand{{\LRpemp}}{{{fmt(c['p_emp'])}}}",
          rf"\newcommand{{\LRpchi}}{{{fmt(c['p_chi2'])}}}", rf"\newcommand{{\LRverdict}}{{{verdict}}}",
          rf"\newcommand{{\LRnullmed}}{{{c['null_median']:.1f}}}", rf"\newcommand{{\LRnullq}}{{{c['null_q95']:.1f}}}",
          rf"\newcommand{{\LRnullsig}}{{{c['null_frac_chi2_sig']:.2f}}}"]
open(out, "w").write("\n".join(L) + "\n")
print(open(out).read())
